export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const OPEN_MODAL = 'OPEN_MODAL'
export const LOGIN_MODE = 'LOGIN_MODE'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const LOGOUT_USER = 'LOGOUT_USER'
export const REGISTER_MODE = 'REGISTER_MODE'
export const USER_INFO_NO_AUTH = 'USER_INFO_NO_AUTH'